version: '3.7'
networks:
  app-tier:
    driver: bridge
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
      args:
        PACKAGIST_AUTH_TOKEN: d86ad04eacf7ad7fd64d7f7887bdba6c5df0a8f61c68ab09b772eb394e98
    restart: unless-stopped
    ports:
      - "9000:80"
    environment:
      APP_DEBUG: "true"
      APP_NAME: "Booking service"
      APP_ENV: local
      DB_HOST: database
      DB_DATABASE: homestead
      DB_USERNAME: homestead
      DB_PASSWORD: secret
      BROADCAST_DRIVER: log
      MACHINE_CLIENT_ID: 41
      MACHINE_SECRET: IEaHF26zdAzT6nLtViov2xmDHvkM3fSJ08wTuSZZ
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: null
      REDIS_HOST: redis
      WAIT_HOSTS: database:3306
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:cached
      - /var/www/html/vendor
      - /var/www/html/bootstrap/cache
      - /var/www/html/vendor/
      - /var/www/html/node_modules
      - /var/www/html/public/dist
    links:
      - redis:cache
      - database
    depends_on:
      - database
      - redis
    networks:
      - app-tier
  redis:
    image: redis:4-alpine
    networks:
      - app-tier
    ports:
      - 16379:6379
  database:
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    networks:
      - app-tier
volumes:
  mysql:
    driver: "local"
