#
# PHP Composer dependencies
#
FROM composer:1.10.1 as vendor

ARG PACKAGIST_AUTH_TOKEN
COPY database database/
COPY composer.json composer.json
COPY composer.lock composer.lock
COPY tests tests/

RUN composer config --global --auth http-basic.repo.packagist.com token $PACKAGIST_AUTH_TOKEN
RUN composer install \
    --ignore-platform-reqs \
    --no-interaction \
    --no-plugins \
    --no-scripts \
    --prefer-dist

#
# Application
#
FROM nginx:1.17.9-alpine

RUN apk add --no-cache php php-fpm php-pdo php-json php-xml php-simplexml php-xmlwriter php-session php-tokenizer php-ctype php-openssl \
    php-mbstring php-gettext php-curl php-zip php-dom php-fileinfo php-mysqli php-pdo_mysql php7-pecl-redis php-bcmath php-gd \
    supervisor && rm -fr /etc/nginx /etc/supervisor

COPY . /var/www/html
COPY --from=vendor /app/vendor/ /var/www/html/vendor/

COPY docker/config/ /etc
COPY docker/config/supervisor/stop-supervisor.sh /etc/supervisor
COPY docker/bootstrap-application /etc/bootstrap-application

RUN chmod +x /etc/supervisor/stop-supervisor.sh && \
    mv /var/www/html/docker/config/ /etc && \
    #chown -R nginx:nginx /var/www/html && \
    touch /var/www/html/storage/logs/queue-worker.log && \
    touch /var/www/html/storage/logs/laravel.log && \
    chmod -R 777 /var/www/html/bootstrap/cache && \
    chmod 777 /var/www/html/storage/logs/laravel.log && \
    chmod +x /etc/bootstrap-application

## THE LIFE SAVER
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait

CMD ["/etc/bootstrap-application"]
